# Codecov configuration for mytradingjournal
# Docs: https://docs.codecov.com/docs/codecov-yaml

codecov:
  require_ci_to_pass: true
  max_report_age: 2

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  hide_project_coverage: false

coverage:
  precision: 2
  round: nearest
  range: 60..100
  status:
    project:
      default:
        target: 85%
        threshold: 1%
        if_not_found: success
      lib:
        paths: ["lib/"]
        target: 85%
        threshold: 2%
      components:
        paths: ["components/"]
        target: 85%
        threshold: 2%
    patch:
      default:
        target: 85%
        threshold: 1%
        if_not_found: success
    changes: off

ignore:
  - "tests/**"
  - "prisma/**"
  - "scripts/**"
  - "vitest.setup.ts"
  - "**/*.d.ts"

flags:
  unit:
    paths:
      - lib/
      - components/
    carryforward: true
  accessibility:
    paths:
      - tests/accessibility-*.test.tsx
    carryforward: true

# Disable coverage for generated prisma client code if present (node_modules excluded by default)

git:
  # Improve matching when rebasing
  detect_missing_files: true
