name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: file:./prisma/dev.db
      ENABLE_PDF_EXPORT: 'false'
      ENABLE_EXPORT_QUEUE: 'false'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Prepare SQLite (shadow) DB
        run: |
          npx prisma migrate deploy || echo 'No migrations to deploy'

      - name: Type check
        run: npm run type-check

      - name: Lint
        run: npm run lint

      - name: Run tests
        run: npm test -- --reporter=default

      - name: Design contrast audit
        run: npm run design:audit

  contrast-regression:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps (prod only)
        run: npm ci --omit=dev || npm ci

      - name: Run contrast audit (fail on regression)
        run: node scripts/contrast-audit.mjs --ci
